//----------------------------------------------------------------------- 
// PDS WITSMLstudio Store, 2018.3
//
// Copyright 2018 PDS Americas LLC
// 
// Licensed under the PDS Open Source WITSML Product License Agreement (the
// "License"); you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//   
//     http://www.pds.group/WITSMLstudio/OpenSource/ProductLicenseAgreement
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//-----------------------------------------------------------------------

// ----------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Energistics.DataAccess;
using Energistics.DataAccess.WITSML141;
using Energistics.DataAccess.WITSML141.ComponentSchemas;
using Energistics.DataAccess.WITSML141.ReferenceData;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace PDS.WITSMLstudio.Store.Data.DownholeComponents
{
    public abstract partial class DownholeComponent141TestBase : IntegrationTestFixtureBase<DevKit141Aspect>
    {
        public const string QueryMissingNamespace = "<downholeComponents version=\"1.4.1.1\"><downholeComponent /></downholeComponents>";
        public const string QueryInvalidNamespace = "<downholeComponents xmlns=\"www.witsml.org/schemas/123\" version=\"1.4.1.1\"></downholeComponents>";
        public const string QueryMissingVersion = "<downholeComponents xmlns=\"http://www.witsml.org/schemas/1series\"></downholeComponents>";
        public const string QueryEmptyRoot = "<downholeComponents xmlns=\"http://www.witsml.org/schemas/1series\" version=\"1.4.1.1\"></downholeComponents>";
        public const string QueryEmptyObject = "<downholeComponents xmlns=\"http://www.witsml.org/schemas/1series\" version=\"1.4.1.1\"><downholeComponent /></downholeComponents>";
        public const string BasicXMLTemplate = "<downholeComponents xmlns=\"http://www.witsml.org/schemas/1series\" version=\"1.4.1.1\"><downholeComponent uidWell=\"{0}\" uid=\"{1}\">{2}</downholeComponent></downholeComponents>";

        protected DownholeComponent141TestBase(bool isEtpTest = false)
            : base(isEtpTest)
        {
        }

        public Well Well { get; set; }
        public DownholeComponent DownholeComponent { get; set; }
        public List<DownholeComponent> QueryEmptyList { get; set; }

        protected override void PrepareData()
        {

            DevKit.Store.CapServerProviders = DevKit.Store.CapServerProviders
                .Where(x => x.DataSchemaVersion == OptionsIn.DataVersion.Version141.Value)
                .ToArray();

            Well = new Well
            {
                Uid = DevKit.Uid(),
                Name = DevKit.Name("Well"),
                TimeZone = DevKit.TimeZone
            };
            DownholeComponent = new DownholeComponent
            {
                Uid = DevKit.Uid(),
                Name = DevKit.Name("DownholeComponent"),
                UidWell = Well.Uid,
                NameWell = Well.Name,
            };

            QueryEmptyList = DevKit.List(new DownholeComponent());

        }

        protected virtual void AddParents()
        {
            DevKit.AddAndAssert<WellList, Well>(Well);
        }
    }
}