//----------------------------------------------------------------------- 
// PDS WITSMLstudio Store, 2018.3
//
// Copyright 2018 PDS Americas LLC
// 
// Licensed under the PDS Open Source WITSML Product License Agreement (the
// "License"); you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//   
//     http://www.pds.group/WITSMLstudio/OpenSource/ProductLicenseAgreement
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//-----------------------------------------------------------------------

// ----------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------

using Energistics.DataAccess;
using Energistics.DataAccess.WITSML141;
using Energistics.DataAccess.WITSML141.ComponentSchemas;
using Energistics.DataAccess.WITSML141.ReferenceData;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;

namespace PDS.WITSMLstudio.Store.Data.MudLogs
{
    [TestClass]
    public partial class MudLog141StoreTests : MudLog141TestBase
    {
        public MudLog141StoreTests()
            : base(false)
        {
        }

        [TestMethod]
        public void MudLog141DataAdapter_GetFromStore_Can_Get_MudLog()
        {
            AddParents();
            DevKit.AddAndAssert<MudLogList, MudLog>(MudLog);
            DevKit.GetAndAssert<MudLogList, MudLog>(MudLog);
       }

        [TestMethod]
        public void MudLog141DataAdapter_AddToStore_Can_Add_MudLog()
        {
            AddParents();
            DevKit.AddAndAssert<MudLogList, MudLog>(MudLog);
        }

        [TestMethod]
        public void MudLog141DataAdapter_UpdateInStore_Can_Update_MudLog()
        {
            AddParents();
            DevKit.AddAndAssert<MudLogList, MudLog>(MudLog);
            DevKit.UpdateAndAssert<MudLogList, MudLog>(MudLog);
            DevKit.GetAndAssert<MudLogList, MudLog>(MudLog);
        }

        [TestMethod]
        public void MudLog141DataAdapter_DeleteFromStore_Can_Delete_MudLog()
        {
            AddParents();
            DevKit.AddAndAssert<MudLogList, MudLog>(MudLog);
            DevKit.DeleteAndAssert<MudLogList, MudLog>(MudLog);
            DevKit.GetAndAssert<MudLogList, MudLog>(MudLog, isNotNull: false);
        }

        [TestMethod]
        public void MudLog141WitsmlStore_GetFromStore_Can_Transform_MudLog()
        {
            AddParents();
            DevKit.AddAndAssert<MudLogList, MudLog>(MudLog);

            // Re-initialize all capServer providers
            DevKit.Store.CapServerProviders = null;
            DevKit.Container.BuildUp(DevKit.Store);

            string typeIn, queryIn;
            var query = DevKit.List(DevKit.CreateQuery(MudLog));
            DevKit.SetupParameters<MudLogList, MudLog>(query, ObjectTypes.MudLog, out typeIn, out queryIn);

            var options = OptionsIn.Join(OptionsIn.ReturnElements.All, OptionsIn.DataVersion.Version131);
            var request = new WMLS_GetFromStoreRequest(typeIn, queryIn, options, null);
            var response = DevKit.Store.WMLS_GetFromStore(request);

            Assert.IsFalse(string.IsNullOrWhiteSpace(response.XMLout));
            Assert.AreEqual((short)ErrorCodes.Success, response.Result);

            var result = WitsmlParser.Parse(response.XMLout);
            var version = ObjectTypes.GetVersion(result.Root);
            Assert.AreEqual(OptionsIn.DataVersion.Version131.Value, version);
        }

        [TestMethod]
        public void MudLog141DataAdapter_AddToStore_Creates_ChangeLog()
        {
            AddParents();

            DevKit.AddAndAssert<MudLogList, MudLog>(MudLog);

            var result = DevKit.GetAndAssert<MudLogList, MudLog>(MudLog);
            var expectedHistoryCount = 1;
            var expectedChangeType = ChangeInfoType.add;
            DevKit.AssertChangeLog(result, expectedHistoryCount, expectedChangeType);
        }

        [TestMethod]
        public void MudLog141DataAdapter_UpdateInStore_Updates_ChangeLog()
        {
            AddParents();

            DevKit.AddAndAssert<MudLogList, MudLog>(MudLog);

            // Update the MudLog141
            MudLog.Name = "Change";
            DevKit.UpdateAndAssert(MudLog);

            var result = DevKit.GetAndAssert<MudLogList, MudLog>(MudLog);
            var expectedHistoryCount = 2;
            var expectedChangeType = ChangeInfoType.update;
            DevKit.AssertChangeLog(result, expectedHistoryCount, expectedChangeType);
        }

        [TestMethod]
        public void MudLog141DataAdapter_DeleteFromStore_Updates_ChangeLog()
        {
            AddParents();

            DevKit.AddAndAssert<MudLogList, MudLog>(MudLog);

            // Delete the MudLog141
            DevKit.DeleteAndAssert(MudLog);

            var expectedHistoryCount = 2;
            var expectedChangeType = ChangeInfoType.delete;
            DevKit.AssertChangeLog(MudLog, expectedHistoryCount, expectedChangeType);
        }

        [TestMethod]
        public void MudLog141DataAdapter_ChangeLog_Tracks_ChangeHistory_For_Add_Update_Delete()
        {
            AddParents();

            // Add the MudLog141
            DevKit.AddAndAssert<MudLogList, MudLog>(MudLog);

            // Verify ChangeLog for Add
            var result = DevKit.GetAndAssert<MudLogList, MudLog>(MudLog);
            var expectedHistoryCount = 1;
            var expectedChangeType = ChangeInfoType.add;
            DevKit.AssertChangeLog(result, expectedHistoryCount, expectedChangeType);

            // Update the MudLog141
            MudLog.Name = "Change";
            DevKit.UpdateAndAssert(MudLog);

            result = DevKit.GetAndAssert<MudLogList, MudLog>(MudLog);
            expectedHistoryCount = 2;
            expectedChangeType = ChangeInfoType.update;
            DevKit.AssertChangeLog(result, expectedHistoryCount, expectedChangeType);

            // Delete the MudLog141
            DevKit.DeleteAndAssert(MudLog);

            expectedHistoryCount = 3;
            expectedChangeType = ChangeInfoType.delete;
            DevKit.AssertChangeLog(MudLog, expectedHistoryCount, expectedChangeType);

            // Re-add the same MudLog141...
            DevKit.AddAndAssert<MudLogList, MudLog>(MudLog);

            //... the same changeLog should be reused.
            result = DevKit.GetAndAssert<MudLogList, MudLog>(MudLog);
            expectedHistoryCount = 4;
            expectedChangeType = ChangeInfoType.add;
            DevKit.AssertChangeLog(result, expectedHistoryCount, expectedChangeType);

            DevKit.AssertChangeHistoryTimesUnique(result);
        }

        [TestMethod]
        public void MudLog141DataAdapter_GetFromStore_Filter_ExtensionNameValue()
        {
            AddParents();

            var extensionName1 = DevKit.ExtensionNameValue("Ext-1", "1.0", "m");
            var extensionName2 = DevKit.ExtensionNameValue("Ext-2", "2.0", "cm", PrimitiveType.@float);
            extensionName2.MeasureClass = MeasureClass.Length;
            var extensionName3 = DevKit.ExtensionNameValue("Ext-3", "3.0", "cm", PrimitiveType.unknown);

            MudLog.CommonData = new CommonData()
            {
                ExtensionNameValue = new List<ExtensionNameValue>()
                {
                    extensionName1, extensionName2, extensionName3
                }
            };

            // Add the MudLog141
            DevKit.AddAndAssert(MudLog);

            // Query for first extension
            var commonDataXml = "<commonData>" + Environment.NewLine +
                                "<extensionNameValue uid=\"\">" + Environment.NewLine +
                                "<name />{0}" + Environment.NewLine +
                                "</extensionNameValue>" + Environment.NewLine +
                                "</commonData>";

            var extValueQuery = string.Format(commonDataXml, "<dataType>double</dataType>");
            var queryXml = string.Format(BasicXMLTemplate, MudLog.UidWell, MudLog.UidWellbore, MudLog.Uid, extValueQuery);
            var result = DevKit.Query<MudLogList, MudLog>(ObjectTypes.MudLog, queryXml, null, OptionsIn.ReturnElements.Requested);
            Assert.IsNotNull(result);
            Assert.AreEqual(1, result.Count);

            var resultMudLog = result[0];
            Assert.IsNotNull(resultMudLog);

            var commonData = resultMudLog.CommonData;
            Assert.IsNotNull(commonData);
            Assert.AreEqual(1, commonData.ExtensionNameValue.Count);

            var env = commonData.ExtensionNameValue[0];
            Assert.IsNotNull(env);
            Assert.AreEqual(extensionName1.Uid, env.Uid);
            Assert.AreEqual(extensionName1.Name, env.Name);

            // Query for second extension
            extValueQuery = string.Format(commonDataXml, "<measureClass>length</measureClass>");
            queryXml = string.Format(BasicXMLTemplate, MudLog.UidWell, MudLog.UidWellbore, MudLog.Uid, extValueQuery);
            result = DevKit.Query<MudLogList, MudLog>(ObjectTypes.MudLog, queryXml, null, OptionsIn.ReturnElements.Requested);
            Assert.IsNotNull(result);
            Assert.AreEqual(1, result.Count);

            resultMudLog = result[0];
            Assert.IsNotNull(resultMudLog);

            commonData = resultMudLog.CommonData;
            Assert.IsNotNull(commonData);
            Assert.AreEqual(1, commonData.ExtensionNameValue.Count);

            env = commonData.ExtensionNameValue[0];
            Assert.IsNotNull(env);
            Assert.AreEqual(extensionName2.Uid, env.Uid);
            Assert.AreEqual(extensionName2.Name, env.Name);

            // Query for third extension
            extValueQuery = string.Format(commonDataXml, "<dataType>unknown</dataType>");
            queryXml = string.Format(BasicXMLTemplate, MudLog.UidWell, MudLog.UidWellbore, MudLog.Uid, extValueQuery);
            result = DevKit.Query<MudLogList, MudLog>(ObjectTypes.MudLog, queryXml, null, OptionsIn.ReturnElements.Requested);
            Assert.IsNotNull(result);
            Assert.AreEqual(1, result.Count);

            resultMudLog = result[0];
            Assert.IsNotNull(resultMudLog);

            commonData = resultMudLog.CommonData;
            Assert.IsNotNull(commonData);
            Assert.AreEqual(1, commonData.ExtensionNameValue.Count);

            env = commonData.ExtensionNameValue[0];
            Assert.IsNotNull(env);
            Assert.AreEqual(extensionName3.Uid, env.Uid);
            Assert.AreEqual(extensionName3.Name, env.Name);
        }

        [TestMethod]
        public void MudLog141DataAdapter_ChangeLog_Syncs_MudLog_Name_Changes()
        {
            AddParents();

            // Add the MudLog141
            DevKit.AddAndAssert<MudLogList, MudLog>(MudLog);

            // Assert that all MudLog names match corresponding changeLog names
            DevKit.AssertChangeLogNames(MudLog);

            // Update the MudLog141 names
            MudLog.Name = "Change";
            MudLog.NameWell = "Well Name Change";

            MudLog.NameWellbore = "Wellbore Name Change";

            DevKit.UpdateAndAssert(MudLog);

            // Assert that all MudLog names match corresponding changeLog names
            DevKit.AssertChangeLogNames(MudLog);
        }

        [TestMethod]
        public void MudLog141DataAdapter_MudLog_ObjectGrowing_Not_Toggled_By_Client()
        {
            AddParents();

            // Set the object growing flag to true
            MudLog.ObjectGrowing = true;

            // Add the MudLog141
            DevKit.AddAndAssert<MudLogList, MudLog>(MudLog);

            // Assert MudLog141 is not growing
            var result = DevKit.GetAndAssert(MudLog);
            Assert.IsFalse(result.ObjectGrowing.GetValueOrDefault(), "MudLog ObjectGrowing");

            DevKit.UpdateAndAssert(MudLog);

            // Assert MudLog141 is not growing
            result = DevKit.GetAndAssert(MudLog);
            Assert.IsFalse(result.ObjectGrowing.GetValueOrDefault(), "MudLog ObjectGrowing");
        }
    }
}