//----------------------------------------------------------------------- 
// PDS WITSMLstudio Store, 2018.3
//
// Copyright 2018 PDS Americas LLC
// 
// Licensed under the PDS Open Source WITSML Product License Agreement (the
// "License"); you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//   
//     http://www.pds.group/WITSMLstudio/OpenSource/ProductLicenseAgreement
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//-----------------------------------------------------------------------

// ----------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------

using Energistics.DataAccess;
using Energistics.DataAccess.WITSML131;
using Energistics.DataAccess.WITSML131.ComponentSchemas;
using Energistics.DataAccess.WITSML131.ReferenceData;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace PDS.WITSMLstudio.Store.Data.Logs
{
    [TestClass]
    public partial class Log131StoreTests : Log131TestBase
    {
        public Log131StoreTests()
            : base(false)
        {
        }

        [TestMethod]
        public void Log131DataAdapter_GetFromStore_Can_Get_Log()
        {
            AddParents();
            DevKit.AddAndAssert<LogList, Log>(Log);
            DevKit.GetAndAssert<LogList, Log>(Log);
       }

        [TestMethod]
        public void Log131DataAdapter_AddToStore_Can_Add_Log()
        {
            AddParents();
            DevKit.AddAndAssert<LogList, Log>(Log);
        }

        [TestMethod]
        public void Log131DataAdapter_UpdateInStore_Can_Update_Log()
        {
            AddParents();
            DevKit.AddAndAssert<LogList, Log>(Log);
            DevKit.UpdateAndAssert<LogList, Log>(Log);
            DevKit.GetAndAssert<LogList, Log>(Log);
        }

        [TestMethod]
        public void Log131DataAdapter_DeleteFromStore_Can_Delete_Log()
        {
            AddParents();
            DevKit.AddAndAssert<LogList, Log>(Log);
            DevKit.DeleteAndAssert<LogList, Log>(Log);
            DevKit.GetAndAssert<LogList, Log>(Log, isNotNull: false);
        }

        [TestMethod]
        public void Log131WitsmlStore_GetFromStore_Can_Transform_Log()
        {
            AddParents();
            DevKit.AddAndAssert<LogList, Log>(Log);

            // Re-initialize all capServer providers
            DevKit.Store.CapServerProviders = null;
            DevKit.Container.BuildUp(DevKit.Store);

            string typeIn, queryIn;
            var query = DevKit.List(DevKit.CreateQuery(Log));
            DevKit.SetupParameters<LogList, Log>(query, ObjectTypes.Log, out typeIn, out queryIn);

            var options = OptionsIn.Join(OptionsIn.ReturnElements.All, OptionsIn.DataVersion.Version141);
            var request = new WMLS_GetFromStoreRequest(typeIn, queryIn, options, null);
            var response = DevKit.Store.WMLS_GetFromStore(request);

            Assert.IsFalse(string.IsNullOrWhiteSpace(response.XMLout));
            Assert.AreEqual((short)ErrorCodes.Success, response.Result);

            var result = WitsmlParser.Parse(response.XMLout);
            var version = ObjectTypes.GetVersion(result.Root);
            Assert.AreEqual(OptionsIn.DataVersion.Version141.Value, version);
        }

        [TestMethod]
        public void Log131DataAdapter_Log_ObjectGrowing_Not_Toggled_By_Client()
        {
            AddParents();

            // Set the object growing flag to true
            Log.ObjectGrowing = true;

            // Add the Log131
            DevKit.AddAndAssert<LogList, Log>(Log);

            // Assert Log131 is not growing
            var result = DevKit.GetAndAssert(Log);
            Assert.IsFalse(result.ObjectGrowing.GetValueOrDefault(), "Log ObjectGrowing");

            DevKit.UpdateAndAssert(Log);

            // Assert Log131 is not growing
            result = DevKit.GetAndAssert(Log);
            Assert.IsFalse(result.ObjectGrowing.GetValueOrDefault(), "Log ObjectGrowing");
        }
    }
}