//----------------------------------------------------------------------- 
// PDS WITSMLstudio Core, 2018.3
//
// Copyright 2018 PDS Americas LLC
// 
// Licensed under the PDS Open Source WITSML Product License Agreement (the
// "License"); you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//   
//     http://www.pds.group/WITSMLstudio/OpenSource/ProductLicenseAgreement
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//-----------------------------------------------------------------------

// ----------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------
namespace PDS.WITSMLstudio
{
    /// <summary>
    /// Defines constants that can be used to indicate a data object's type.
    /// </summary>
    public static partial class ObjectTypes
    {
        /// <summary>
        /// The data object type for a Activity.
        /// </summary>
        public const string Activity = "activity";

        /// <summary>
        /// The data object type for a ActivityTemplate.
        /// </summary>
        public const string ActivityTemplate = "activityTemplate";

        /// <summary>
        /// The data object type for a Attachment.
        /// </summary>
        public const string Attachment = "attachment";

        /// <summary>
        /// The data object type for a BhaRun.
        /// </summary>
        public const string BhaRun = "bhaRun";

        /// <summary>
        /// The data object type for a CementJob.
        /// </summary>
        public const string CementJob = "cementJob";

        /// <summary>
        /// The data object type for a CementJobEvaluation.
        /// </summary>
        public const string CementJobEvaluation = "cementJobEvaluation";

        /// <summary>
        /// The data object type for a Channel.
        /// </summary>
        public const string Channel = "channel";

        /// <summary>
        /// The data object type for a ChannelSet.
        /// </summary>
        public const string ChannelSet = "channelSet";

        /// <summary>
        /// The data object type for a ConvCore.
        /// </summary>
        public const string ConvCore = "convCore";

        /// <summary>
        /// The data object type for a DataAssuranceRecord.
        /// </summary>
        public const string DataAssuranceRecord = "dataAssuranceRecord";

        /// <summary>
        /// The data object type for a DepthRegImage.
        /// </summary>
        public const string DepthRegImage = "depthRegImage";

        /// <summary>
        /// The data object type for a DownholeComponent.
        /// </summary>
        public const string DownholeComponent = "downholeComponent";

        /// <summary>
        /// The data object type for a DrillReport.
        /// </summary>
        public const string DrillReport = "drillReport";

        /// <summary>
        /// The data object type for a FluidsReport.
        /// </summary>
        public const string FluidsReport = "fluidsReport";

        /// <summary>
        /// The data object type for a FormationMarker.
        /// </summary>
        public const string FormationMarker = "formationMarker";

        /// <summary>
        /// The data object type for a Log.
        /// </summary>
        public const string Log = "log";

        /// <summary>
        /// The data object type for a Message.
        /// </summary>
        public const string Message = "message";

        /// <summary>
        /// The data object type for a MudLog.
        /// </summary>
        public const string MudLog = "mudLog";

        /// <summary>
        /// The data object type for a MudLogReport.
        /// </summary>
        public const string MudLogReport = "mudLogReport";

        /// <summary>
        /// The data object type for a OpsReport.
        /// </summary>
        public const string OpsReport = "opsReport";

        /// <summary>
        /// The data object type for a Rig.
        /// </summary>
        public const string Rig = "rig";

        /// <summary>
        /// The data object type for a RigUtilization.
        /// </summary>
        public const string RigUtilization = "rigUtilization";

        /// <summary>
        /// The data object type for a Risk.
        /// </summary>
        public const string Risk = "risk";

        /// <summary>
        /// The data object type for a SidewallCore.
        /// </summary>
        public const string SidewallCore = "sidewallCore";

        /// <summary>
        /// The data object type for a StimJob.
        /// </summary>
        public const string StimJob = "stimJob";

        /// <summary>
        /// The data object type for a StimJobStage.
        /// </summary>
        public const string StimJobStage = "stimJobStage";

        /// <summary>
        /// The data object type for a SurveyProgram.
        /// </summary>
        public const string SurveyProgram = "surveyProgram";

        /// <summary>
        /// The data object type for a Target.
        /// </summary>
        public const string Target = "target";

        /// <summary>
        /// The data object type for a ToolErrorModel.
        /// </summary>
        public const string ToolErrorModel = "toolErrorModel";

        /// <summary>
        /// The data object type for a ToolErrorTermSet.
        /// </summary>
        public const string ToolErrorTermSet = "toolErrorTermSet";

        /// <summary>
        /// The data object type for a Trajectory.
        /// </summary>
        public const string Trajectory = "trajectory";

        /// <summary>
        /// The data object type for a Tubular.
        /// </summary>
        public const string Tubular = "tubular";

        /// <summary>
        /// The data object type for a WbGeometry.
        /// </summary>
        public const string WbGeometry = "wbGeometry";

        /// <summary>
        /// The data object type for a Well.
        /// </summary>
        public const string Well = "well";

        /// <summary>
        /// The data object type for a Wellbore.
        /// </summary>
        public const string Wellbore = "wellbore";

        /// <summary>
        /// The data object type for a WellboreCompletion.
        /// </summary>
        public const string WellboreCompletion = "wellboreCompletion";

        /// <summary>
        /// The data object type for a WellboreGeology.
        /// </summary>
        public const string WellboreGeology = "wellboreGeology";

        /// <summary>
        /// The data object type for a WellboreGeometry.
        /// </summary>
        public const string WellboreGeometry = "wellboreGeometry";

        /// <summary>
        /// The data object type for a WellboreMarker.
        /// </summary>
        public const string WellboreMarker = "wellboreMarker";

        /// <summary>
        /// The data object type for a WellboreMarkerSet.
        /// </summary>
        public const string WellboreMarkerSet = "wellboreMarkerSet";

        /// <summary>
        /// The data object type for a WellCMLedger.
        /// </summary>
        public const string WellCMLedger = "wellCMLedger";

        /// <summary>
        /// The data object type for a WellCompletion.
        /// </summary>
        public const string WellCompletion = "wellCompletion";

        /// <summary>
        /// The data object type for a WellLog.
        /// </summary>
        public const string WellLog = "wellLog";

    }
}